version: "3.8"

networks:
  bookstore_network:  # Criação da rede personalizada

services:
  db:
    image: mysql:8.0
    container_name: bookstore_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bookstore_dev_db
      MYSQL_USER: bookstore_dev
      MYSQL_PASSWORD: bookstore_dev
    ports:
      - "3306:3306"
    networks:
      - bookstore_network  # Conectando ao MySQL

  web:
    build: .
    container_name: bookstore_web
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DATABASE_URL: "mysql://bookstore_dev:bookstore_dev@db:3306/bookstore_dev_db"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - bookstore_network  # Conectando ao Django

volumes:
  mysql_data: