version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: bookstore_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bookstore_dev_db
      MYSQL_USER: bookstore_dev
      MYSQL_PASSWORD: bookstore_dev
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: bookstore_web
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DATABASE_URL: "mysql://bookstore_dev:bookstore_dev@db:3306/bookstore_dev_db"
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql_data: