
networks:
  bookstore_network:  # Criando uma rede personalizada para permitir a comunicação entre serviços.

services:
  db:
    image: postgres:latest
    container_name: bookstore_db
    environment:
      POSTGRES_DB: bookstore_dev
      POSTGRES_USER: bookstore_dev
      POSTGRES_PASSWORD: bookstore_dev
    ports:
      - "5432:5432"
    networks:
      - bookstore_network
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Configurando persistência dos dados

  web:  # Serviço para a aplicação web.
    build: .  # Define que o contêiner será construído a partir do diretório atual.
    depends_on:
      - db  # Garante que o serviço 'db' seja iniciado antes do 'web'
    entrypoint: ["./wait-for-db.sh", "db", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    networks:
      - bookstore_network  # Conecta a aplicação à rede personalizada.
    environment:
      DATABASE_URL: "postgres://bookstore_dev:bookstore_dev@db:5432/bookstore_dev"

volumes:
  postgres_data:  # Volume correto para armazenar dados do PostgreSQL