version: "3.8"
services:
  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_USER: bookstore_dev
      POSTGRES_PASSWORD: bookstore_dev
      POSTGRES_DB: bookstore_dev_db
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db